### ISSUE TITLE
Show as Taskboard button not displaying for some users

### ISSUE THREAD

**Issue by softsolutionsau** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#46] opened 2021-03-18 18:02 UTC
Hi, 

We installed this (amazing, by the way) plug in a few days ago. I'm seeing strange issue where some users are seeing the above button but others are not. They are both in the same organization and project. Identical permissions and licensing.

I've asked those that cannot see this button to restart/refresh/clear cache. Both Chrome and Edge.

Any guidance very much appreciated :)

Shai

**Comment by edtro** [comment] 2021-03-18 18:42
@softsolutionsau  Dear Shai,
This is not the expected behaviour.

A button should always been shown for 'Flat' or 'One-Hop' queries. When you select the 'Tree' option the button is hidden, because this type is not implemented. That is the only situation that I can think of that could be an issue. But if the same query can be used by an other user, and displayed as a board... well we have to look a little bit further.

So to be able to help you, I really need some more detailled information... 
What kind of organization is it, is it an On Line or an On Premise (what version)?
Can you see any errors within the console (within the developer tools of the browser - F12)?

Kr
Edward

**Comment by edtro** [comment] 2021-03-18 18:55
One thing you can try is the following:
- First make sure within the browser session, you have opened a query with my extension succesfully and displayed it as a board. This caches the extensions sources and will allow you to use a url directly. (btw: unfortunately the Azure DevOps Framework / SDK does not allow when it is not cached, it seems.... I have reported an issue at Microsoft but they are not responding)
- Use the following url: `{your org url}/{your teamproject}/_queries/realdolmen.EdTro-AzureDevOps-Extensions-QueryBasedBoards-Public.EdTro-AzureDevOps-Extensions-QueryBasedBoards.BoardTab/{your query guid}/`

Normally the url for a query is as follows: `{your org url}/{your teamproject}/_queries/query/{your query guid}/`

Kr Edward.

**Comment by edtro** [comment] 2021-03-20 07:10
@softsolutionsau 
Dear Shai,
I am hoping to get some more information, because I am really committed to get this problem solved.

Also I have an other suggestion you could try: try installing this extension: https://marketplace.visualstudio.com/items?itemName=ms-samples.samples-contributions-guide and see if all of the users are getting the new tab called 'WebContext'. 

This way we can rule out if it is problem within Azure DevOps itself (that it isn't picking up all of the items from the installed extensions... I have seen strange behaviour within the Project Settings menu, where menu items didn't show up  even from the 'standard' extensions).

Kr
Edward

**Comment by edtro** [comment] 2021-03-20 07:18
Next to this, there is something you could check.

Someone else has mentioned (within this issue: https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/issues/45 ), that queries within a subfolder (possibly with extra permissions setup) didn't run well. He had solved this... but I wasn't able to reproduce this problem. So is this query that is having this problem, within a subfolder?

Kr
Edward

> Note: you have certainly already noticed that I am using this issue to sum up all of the possible methods I can think of to troubleshoot this extension :-)

**Comment by edtro** [comment] 2021-03-29 06:23
Dear @softsolutionsau,
The fact remains that I am very committed to resolve this problem, but however without receiving any response or (detailled) input, I am not able to reproduce and resolve this problem. 

So this is a nice reminder... so can you please respond.
Kr
Edward

**Comment by edtro** [comment] 2021-04-23 05:15
Dear @softsolutionsau ,
Because I have not received any feedback, I am forced to close this issue without resolving it.
When you provide any feedback however, I will reopen it.
Kr
Edward

**Closed by edtro** 2021-04-23 05:15 UTC
